### ISSUE TITLE
All issues found on this webside should be reported here

### ISSUE THREAD

**Issue by ndorrh** [ndorrh/final-capstone#1]
Please kindly summit all your issues here and suggestions and improvements to make the project better

**Comment by OscarFMdev** [comment]
## Hello Ndorrh
I like how your website is looking, however, I notice you can make it even better for all screen sizes if you could:
- [ ] Increase the font-size.
- [ ] [OPTIONAL] Reduce the padding of your mobile menu program section.
- [ ] [OPTIONAL] Add nav bar options interactions on hover.

### Cheers and happy coding! 🙌
