### ISSUE TITLE
Tips to improve your code.

### ISSUE THREAD

**Issue by MahdiSohaily** [ndorrh/final-capstone#3]
We have carefully reviewed your code dear Ndorrah and found it well-organized and clean-coded. 💯 
to highlight:

- good commit message.
- good usage of GitHub workflow.
- well structured.

also there are some suggestions that might improve your code even more.

- Adding javascript files at the head part of the document slows down the document load time. because it will prevent the rest of the document from loading while the JS file is transplanting. so it's a good practice to add your `script` files at the end of the document right before the `body` closing tag also if you want you can place them inside the head tag if you add the `defer` attribute to your `script` tag. [see](https://github.com/ndorrh/final-capstone/blob/main/index.html#L13-L16).
- Nowadays SEO really matters because of the enormous usage of websites and searching for data online. on way to have a good SEO, training is the correct usage of HTML5 semantic tags and one of the good practices in terms of SEO is the proper usage of headings. so we respectfully suggest using the heading base on their priority from top to bottom (`<h1> - <h6>`). [see](https://github.com/ndorrh/final-capstone/blob/main/index.html#L100-L101)
- Accessibility is one of the core concepts of program development nowadays, clients will reject websites and applications with poor accessibility. one thing that really matters in this term is having a scaleable website. for this purpose, we highly recommend adding `width` and `height` properties to your images, this way it will prevent your document to have reserved space for images even before their loading.
- following the best practices of coding well, improves the code performance and maintenance. so we highly recommend instead of passing arguments using `back tick` syntax use the normal way. [see](https://github.com/ndorrh/final-capstone/blob/home-page/Apps/dynamicHtml.js#L66-L70)

**Comment by ndorrh** [comment]
hi @MahdiSohaily 
Thanks very much for the feedback
